app/models.py
from app import db
from datetime import datetime
import re

from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

post_tags = db.Table('post_tags',
                    db.Column('post_id', db.Integer(), db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer(), db.ForeignKey('tag.id'))
    )


class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def generateslug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __init__ (self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generateslug()


    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))



    def __repr__(self):
        return '{}'.format(self.title)

class Tag(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def generateslug(self):
        if self.name:
            self.slug = slugify(self.name)+'-tag'

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.generateslug()

    def __repr__(self):
        return '{}'.format(self.name)

### Flask Security
roles_users = db.Table('role_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/app.py
from flask import Flask, redirect, request, url_for
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security, current_user



app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)
### Admin ###
from models import *

class AdminMixin:
        def is_accessible(self):
            return current_user.has_role('admin')

        def inaccessible_callback(self, name, **kwargs):
            return redirect(url_for('security.login', next=request.url))

class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generateslug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

class AdminView(AdminMixin, ModelView):
    pass

class HomeAdminView(AdminMixin, AdminIndexView):
    pass

class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title','body', 'tags']

class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']

admin = Admin(app, 'Flaskapp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

###Flask Security###
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

app/main.py
from app import app
import view
from app import db
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post, Tag
from flask import request
from .forms import PostForm
from app import db
from flask import redirect, url_for
from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        post = Post(title=title, body=body)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)

@posts.route('/<slug>/edit/', methods=['POST','GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)

@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) #.all()
    else:
        posts = Post.query.order_by(Post.created.desc())


    pages = posts.paginate(page=page, per_page=10)

    return render_template('posts/index.html', posts=posts, pages=pages)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  New Post
{% endblock %}

{% block content_title %}
  New Post
{% endblock %}

{% block content %}
  <div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method='POST'>
      {% for field in form %}
        <div class="form group">
          {{ field.label(class="control-label") }}
          {{ field(class="form-control") }}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>


{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
  Edit Post
{% endblock %}

{% block content_title %}
  Edit Post
{% endblock %}

{% block content %}
  <div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method='POST'>
      {% for field in form %}
        <div class="form group">
          {{ field.label(class="control-label") }}
          {{ field(class="form-control") }}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">Edit</button>
    </form>
  </div>


{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  BlueprintIndex Page
{% endblock %}

{% block content_title %}
  Posts
{% endblock %}

{% block content %}
  {% for post in pages.items %}
    <p>
      <a href="{{url_for('posts.post_detail', slug=post.slug) }}"> {{ post.title }} </a>
    </p>
  {% endfor %}
  <nav>
    <ul class="pagination">
      <li
      {% if not pages.has_prev %}
        class="page-item disabled"
      {% endif %}
      >
      <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
      </li>

        {% for page in pages.iter_pages(left_edge=5, left_current=1, right_current=1, right_edge=10) %}
          <li {% if page == pages.page %} class="page-item active" {% endif %}>
            <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
          </li>
        {% endfor %}

      <li
      {% if not pages.has_next %}
        class="page-item disabled"
      {% endif %}
      >
        <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{post.title}}
{% endblock %}

{% block content_title %}
    {{post.title}}
{% endblock %}

{% block content %}
  <div class="tags">
    {% for tag in tags %}
    <a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}"><span class="badge badge-pill badge-success">{{ tag.name }}</span></a>
    {% endfor %}
  </div>
  <div class="main_content">
    {{post.body}}
  </div>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ tag.name }} posts
{% endblock %}

{% block content_title %}
  Posts for "{{ tag.name }}"
{% endblock %}

{% block content %}
  {% for post in posts %}
    <p>
      <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
    </p>
  {% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}

    {% endblock %} | Flask app
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href=" {{ url_for('index') }} ">Flask</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href=" {{ url_for('posts.index') }} ">Blog <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=" {{ url_for('posts.create_post' )}}">New Post</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
            {% if current_user.has_role('admin') %}
          <a class="nav-link" href="/admin" tabindex="-1" aria-disabled="true">Administration</a>
          {% endif %}
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="/blog/" method="GET">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" value="{{ request.args.get('q', '') }}"aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div class="container">
      <h1>
        {% block content_title %}

        {% endblock %}
      </h1>
      {% block content %}

      {% endblock %}
  </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}

  Index page

{% endblock %}

{% block content_title %}
  Index page
{% endblock %}

{% block content %}
  Some content
{% endblock %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  </div>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content_title %}
<div class="blockquote text-center">
    <h1>Login</h1>
</div>

{% endblock %}

{% block content %}
<div class="col-sm-4 offset-md-4">
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
    {{ login_user_form.hidden_tag() }}
    {{ render_field_with_errors(login_user_form.email, class="form-control") }}
    {{ render_field_with_errors(login_user_form.password, class="form-control") }}
    {{ render_field_with_errors(login_user_form.remember) }}
    {{ render_field(login_user_form.next) }}
    {{ render_field(login_user_form.submit, class="btn btn-primary") }}
  </form>
  {% include "security/_menu.html" %}
</div>

{% endblock %}